-- v16 additions: employee documents + storage bucket (Supabase)
-- Safe to run multiple times.

-- 1) Documents table
create table if not exists public.employee_documents (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.employees(id) on delete cascade,
  file_name text not null,
  file_path text not null unique,
  doc_type text null,
  created_at timestamptz not null default now()
);

create index if not exists employee_documents_employee_id_idx
  on public.employee_documents(employee_id);

-- 2) Storage bucket for employee docs (service-role uploads)
-- NOTE: This creates the bucket record. If you prefer, you can also create it in Supabase UI (Storage).
do $$
begin
  if not exists (select 1 from storage.buckets where id = 'employee-docs') then
    insert into storage.buckets (id, name, public) values ('employee-docs', 'employee-docs', false);
  end if;
end $$;
